### ISSUE TITLE
Question regarding spike-in normalization

### ISSUE THREAD

**Issue by bartlosz** [rnakato/Churros#2]
Dear authors,

Thank you for providing a great tool to make fast ChIPseq analysis.
I was making the analysis using parameters to include spike-in normalization:
churros -p 24 /home/ubuntu/input/samplelist.txt /home/ubuntu/input/samplepairlist.txt mm39 /home/ubuntu/Referencedata_mm39 --build_spikein dm6 --Ddir_spikein /home/ubuntu/Referencedata_dm6

Pipeline went smoothly, but I cannot find in commands that were executed any relation with my spike-in (dm6). Therefore I have a question how can I verify if my final results are spike-in normalized?

Best regards!

**Comment by miguellords** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by bartlosz** [comment]
Thank you, but not sure what to do with these files, I am using your docker version of the tool

**Comment by rnakato** [comment]
Hi bartlosz,

Thank you for using Churros. To enable spike-in mode, please include the `--spikein` option along with the `--build_spikein` and `--Ddir_spikein` options. Churros will then create the `bigWig/Spikein/`, `pdf_spikein/`, and `spikein_scalingfactor` directories, which contain the results of the spike-in analysis.

Since the spike-in command is quite new and hasn't been thoroughly tested, there may be some problems in certain cases. Please let me know if anything seems wrong.

**Comment by bartlosz** [comment]
Hi,

So in my case I don't have it. I believe spike-in did not work. I am not sure if the step when you download (wget) genome worked correctly for me as I had some warning there.

**Comment by rnakato** [comment]
Yes, because your command does not contain the `--spikein` option. Please add it.

`churros -p 24 --spikein /home/ubuntu/input/samplelist.txt /home/ubuntu/input/samplepairlist.txt mm39 /home/ubuntu/Referencedata_mm39 --build_spikein dm6 --Ddir_spikein /home/ubuntu/Referencedata_dm6`

**Comment by bartlosz** [comment]
Ah, ok, I see your point now, thank you :)
